if(PROBE)
  if(NOT MODE STREQUAL "missing")
    message("public API linked: test-version (42)")
  endif()
  if(MODE STREQUAL "nonzero")
    message(FATAL_ERROR "Injected failure after expected output")
  elseif(MODE STREQUAL "sanitizer")
    message("runtime error: injected UBSan diagnostic")
  endif()
  return()
endif()

execute_process(COMMAND "${CMAKE_COMMAND}" "-DPROGRAM=${CMAKE_COMMAND}"
  "-DPROGRAM_ARGS=-DPROBE=ON;-DMODE=${MODE};-P;${CMAKE_CURRENT_LIST_FILE}"
  "-DEXPECTED=public API linked: test-version (42)" -P "${CHECK}"
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(MODE STREQUAL "success")
  if(NOT "${status}" STREQUAL "0")
    message(FATAL_ERROR "Valid program was rejected:\n${output}${error}")
  endif()
else()
  if(MODE STREQUAL "nonzero")
    set(expected "Program failed")
  elseif(MODE STREQUAL "missing")
    set(expected "Missing expected output")
  else()
    set(expected "Sanitizer diagnostic")
  endif()
  string(FIND "${output}${error}" "${expected}" position)
  if("${status}" STREQUAL "0" OR position EQUAL -1)
    message(FATAL_ERROR "Output gate did not reject ${MODE} correctly:\n${output}${error}")
  endif()
endif()
