# Writes fixture_digests.h from the built side modules. Run through
# cmake -P with -DOUT= and one -D<input>= per artifact.
file(SHA256 "${A}" a_digest)
file(SHA256 "${B}" b_digest)
file(SHA256 "${INCOMPATIBLE}" incompatible_digest)
file(SHA256 "${INCOMPLETE}" incomplete_digest)
file(WRITE "${OUT}"
  "// Generated by generate_digests.cmake from the built fixtures; do not edit.\n"
  "#pragma once\n\n"
  "inline constexpr char a_digest[] = \"${a_digest}\";\n"
  "inline constexpr char b_digest[] = \"${b_digest}\";\n"
  "inline constexpr char incompatible_digest[] = \"${incompatible_digest}\";\n"
  "inline constexpr char incomplete_digest[] = \"${incomplete_digest}\";\n")
